### ISSUE TITLE
[Enhancement] Extend validation to main NE components pull requests

### ISSUE THREAD

**Issue by ignacio-penas** [nuvlaedge/validation#10]
NuvlaEdge validation works on pushes to nuvlaedge/deployment main branch.

The goal is to have the validation system running for:
- [x] Agent
- [x] System Manager nuvlaedge/system-manager#39
- [x] VPN-Client nuvlaedge/vpn-client#2
- [x] Compute-api nuvlaedge/compute-api#6
- [ ] Job engine nuvla/job-engine#254
- [x] on-stop nuvlaedge/on-stop#2
- [x] Facilitate modification of docker-compose.yml file once downloaded with the correct nuvladev images of each microservice
- [x] Read which repository is triggering the validation and parse the branch.

Default base version will be the latest (Including pre-releases).

**Comment by ignacio-penas** [comment]
Close this issue because it's outdated and validation is already integrated with the nuvlaedge software
